enum MaterialCondition { NEW, LIKE_NEW, GOOD, FAIR }
enum MaterialStatus { AVAILABLE, RESERVED, SOLD }
enum MaterialCategory { BOOKS, CALCULATORS, LAB_EQUIPMENT, FURNITURE, OTHER }
enum MeetingZoneType { LIBRARY, STUDENT_CENTER, BUILDING_LOBBY, PLAZA }
enum NotificationType { SMART_MATCH, OTHER }
enum AnalyticsEventType { LISTING_VIEW, SEARCH, CONTACT_SELLER, WISHLIST_ADD, WISHLIST_REMOVE, NOTIFICATION_SENT, NOTIFICATION_OPENED }
